### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/ainulindale#1]
- [ ] Saga upstream calls (`apply` and `compensate`).
- [ ] Adapter-based communication layer for sync (HTTP, HTTP/2, gRPC) or async (RabbitMQ) events.
- [ ] Adapter-based tracing system.
- [ ] Upstream service requests in a declarative way (parallel/sequencial calls with repeats and rollbacks).
- [ ] Cache for upstream services responses.
- [ ] Circut breaker plugin.

Inspiration materials:
- https://www.infoq.com/presentations/microservices-data-centric
- https://linkerd.io/
- problematic code in https://github.com/edenlabllc/ehealth.api
